# Generated by Django 5.1.15 on 2026-09-29 07:05

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('business_type', models.CharField(choices=[('retail', 'Retail'), ('grocery', 'Grocery'), ('restaurant', 'Restaurant'), ('hardware', 'Hardware'), ('clothing', 'Clothing'), ('electronics', 'Electronics'), ('pharmacy', 'Pharmacy'), ('cosmetics', 'Cosmetics'), ('salon', 'Salon'), ('wholesale', 'Wholesale'), ('service', 'Service'), ('other', 'Other')], default='other', max_length=32)),
                ('registration_number', models.CharField(blank=True, default='', max_length=64)),
                ('tax_number', models.CharField(blank=True, default='', max_length=64)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('region', models.CharField(blank=True, default='', max_length=128)),
                ('country', models.CharField(default='Tanzania', max_length=64)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('timezone', models.CharField(default='Africa/Dar_es_Salaam', max_length=64)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='businesses/logos/', validators=[apps.common.validators.validate_image_upload])),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], db_index=True, default='active', max_length=16)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='businesses__status_79852a_idx')],
            },
        ),
    ]
