# Generated by Django 5.1.15 on 2026-09-29 22:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('api_version', models.CharField(default='', max_length=32)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('error', 'Error')], default='active', max_length=16)),
                ('is_primary', models.BooleanField(default=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Null means custom/payer-entered amount.', max_digits=14, null=True)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('custom_amount', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('expired', 'Expired')], default='active', max_length=16)),
                ('payments_count', models.PositiveIntegerField(default=0)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_links', to='businesses.business')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_links', to='billing.paymentprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('external_reference', models.CharField(blank=True, default='', max_length=128)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=32)),
                ('channel', models.CharField(blank=True, default='', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('narration', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=16)),
                ('status_reason', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='businesses.business')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='billing.paymentprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('external_reference', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('channel', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('card', 'Card'), ('bank', 'Bank')], default='mobile_money', max_length=16)),
                ('channel_detail', models.CharField(blank=True, default='', help_text='Provider-reported method, e.g. mpesa, airtel_money.', max_length=32)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=32)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('voided', 'Voided'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=16)),
                ('status_reason', models.TextField(blank=True, default='', help_text='Normalized failure/void/expiry reason from provider.')),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_payments', to='businesses.business')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.paymentprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_reference', models.CharField(max_length=64, unique=True)),
                ('checkout_url', models.URLField(blank=True, default='')),
                ('payment_link_url', models.URLField(blank=True, default='')),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=16)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='businesses.business')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='billing.paymentprovider')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='billing.providerpayment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_reference', models.CharField(db_index=True, max_length=128)),
                ('external_reference', models.CharField(blank=True, default='', max_length=128)),
                ('internal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('external_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('internal_status', models.CharField(blank=True, default='', max_length=32)),
                ('external_status', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('mismatch', 'Mismatch'), ('missing_provider', 'Missing Provider Record'), ('missing_internal', 'Missing Internal Record'), ('pending', 'Pending'), ('manual_review', 'Manual Review')], db_index=True, default='pending', max_length=24)),
                ('notes', models.TextField(blank=True, default='')),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='billing.providerpayment')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation', to='billing.paymentprovider')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_created', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.providerpayment')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.paymentprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=128)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('signature_status', models.CharField(choices=[('verified', 'Signature Verified'), ('invalid', 'Signature Invalid'), ('replay_rejected', 'Replay Rejected')], max_length=24)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Processing Failed'), ('duplicate', 'Duplicate Event')], db_index=True, default='received', max_length=16)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=128)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('processing_ms', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhooks', to='billing.paymentprovider')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('payment.created', 'Payment Created'), ('payment.initiated', 'Payment Initiated'), ('payment.pending', 'Payment Pending'), ('payment.completed', 'Payment Completed'), ('payment.failed', 'Payment Failed'), ('payment.expired', 'Payment Expired'), ('payment.voided', 'Payment Voided'), ('refund.initiated', 'Refund Initiated'), ('refund.completed', 'Refund Completed'), ('payout.initiated', 'Payout Initiated'), ('payout.completed', 'Payout Completed'), ('payout.failed', 'Payout Failed'), ('payout.reversed', 'Payout Reversed')], max_length=32)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('status', models.CharField(blank=True, default='', max_length=16)),
                ('source', models.CharField(default='webhook', help_text='webhook | api | admin', max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='billing.providerpayment')),
                ('webhook_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='billing.webhookevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='providerpayment',
            index=models.Index(fields=['provider', 'status', 'created_at'], name='billing_pro_provide_7b33d4_idx'),
        ),
        migrations.AddIndex(
            model_name='providerpayment',
            index=models.Index(fields=['business', 'status'], name='billing_pro_busines_cc6e5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationrecord',
            constraint=models.UniqueConstraint(fields=('provider', 'internal_reference'), name='unique_recon_per_reference'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_webhook_event_per_provider'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['payment', 'created_at'], name='billing_pay_payment_b83425_idx'),
        ),
    ]
