# Generated by Django 5.1.15 on 2026-09-29 07:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('businesses', '0001_initial'),
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=32)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='branches.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='products.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['business', 'status', 'due_date'], name='invoices_in_busines_d51444_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['business', 'customer'], name='invoices_in_busines_aaf38d_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('business', 'invoice_number'), name='unique_invoice_number_per_business'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice'], name='invoices_in_invoice_bb0f9b_idx'),
        ),
    ]
