# Generated by Django 5.1.15 on 2026-09-29 07:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('SALES', 'Sales'), ('INVENTORY', 'Inventory'), ('CUSTOMERS', 'Customers'), ('FINANCE', 'Finance'), ('REPORTS', 'Reports'), ('STAFF', 'Staff'), ('BRANCHES', 'Branches'), ('NOTIFICATIONS', 'Notifications'), ('EXPORTS', 'Exports'), ('ANALYTICS', 'Analytics'), ('INTEGRATIONS', 'Integrations')], default='REPORTS', max_length=32)),
                ('feature_type', models.CharField(choices=[('BOOLEAN', 'Boolean'), ('LIMIT', 'Limit'), ('CONFIGURED', 'Configured')], default='BOOLEAN', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_interval',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=16),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Shown on the public plan-comparison page.'),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='metric',
            field=models.CharField(choices=[('sales_count', 'Sales Count'), ('products_count', 'Products Count'), ('staff_count', 'Staff Count'), ('branches_count', 'Branches Count'), ('sms_count', 'SMS Count'), ('whatsapp_count', 'WhatsApp Count'), ('invoices_count', 'Invoices Count'), ('report_exports', 'Report Exports')], max_length=32),
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='subscriptions.feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='subscriptions.plan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan', 'feature'), name='unique_plan_feature')],
            },
        ),
    ]
