# Generated by Django 5.1.15 on 2026-09-29 07:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('businesses', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('SALE_RETURN', 'Sale Return'), ('PURCHASE_RETURN', 'Purchase Return'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('DAMAGE', 'Damage'), ('INITIAL_STOCK', 'Initial Stock')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Always positive; direction implied by movement_type.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reference_type', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('reference_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('balance_after', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Stock level after this movement (audit convenience).', max_digits=14)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='branches.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'product', 'created_at'], name='inventory_i_busines_b8a0c4_idx'), models.Index(fields=['business', 'branch', 'created_at'], name='inventory_i_busines_d69250_idx'), models.Index(fields=['reference_type', 'reference_id'], name='inventory_i_referen_0d8590_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='branches.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='businesses.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'branch', 'quantity'], name='inventory_s_busines_9b34a0_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'branch', 'product'), name='unique_stock_level')],
            },
        ),
    ]
