# Generated by Django 5.1.15 on 2026-09-29 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('auth.login', 'Login'), ('auth.login_failed', 'Login Failed'), ('auth.logout', 'Logout'), ('auth.password_change', 'Password Change'), ('auth.password_reset', 'Password Reset'), ('staff.invited', 'Staff Invited'), ('staff.removed', 'Staff Removed'), ('staff.updated', 'Staff Updated'), ('staff.role_changed', 'Role Changed'), ('product.created', 'Product Created'), ('product.updated', 'Product Updated'), ('product.deleted', 'Product Deleted'), ('inventory.adjusted', 'Stock Adjusted'), ('inventory.transferred', 'Stock Transferred'), ('sale.created', 'Sale Created'), ('sale.completed', 'Sale Completed'), ('sale.cancelled', 'Sale Cancelled'), ('sale.refunded', 'Sale Refunded'), ('payment.received', 'Payment Received'), ('expense.created', 'Expense Created'), ('expense.updated', 'Expense Updated'), ('expense.deleted', 'Expense Deleted'), ('invoice.created', 'Invoice Created'), ('invoice.updated', 'Invoice Updated'), ('invoice.cancelled', 'Invoice Cancelled'), ('customer.created', 'Customer Created'), ('customer.updated', 'Customer Updated'), ('supplier.created', 'Supplier Created'), ('supplier.updated', 'Supplier Updated'), ('business.updated', 'Business Updated'), ('subscription.changed', 'Subscription Changed'), ('membership.created', 'Membership Created')], db_index=True, max_length=64)),
                ('resource_type', models.CharField(db_index=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, default='', max_length=64)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='businesses.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'action', 'created_at'], name='audit_audit_busines_887a24_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx')],
            },
        ),
    ]
