# Generated by Django 5.1.15 on 2026-09-29 07:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_alter_branch_business'),
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('sales', 'Sales'), ('inventory', 'Inventory'), ('expenses', 'Expenses'), ('customers', 'Customers'), ('suppliers', 'Suppliers'), ('profit', 'Profit'), ('payments', 'Payments'), ('staff', 'Staff'), ('branches', 'Branches'), ('tax', 'Tax'), ('advanced', 'Advanced Analytics')], max_length=32)),
                ('feature_key', models.CharField(db_index=True, max_length=64)),
                ('capabilities', models.JSONField(default=list)),
                ('supported_filters', models.JSONField(default=list)),
                ('minimum_access_level', models.CharField(choices=[('any', 'Any member'), ('manager', 'Manager+'), ('owner', 'Owner only')], default='any', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=16)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='0=Monday … 6=Sunday (weekly)', null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='1-28 (monthly)', null=True)),
                ('hour', models.PositiveSmallIntegerField(default=8)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF')], default='csv', max_length=8)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled')], db_index=True, default='active', max_length=16)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_reports', to='branches.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='businesses.business')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='report_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.report')),
            ],
            options={
                'ordering': ['next_run_at'],
            },
        ),
        migrations.CreateModel(
            name='EntitlementEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('access_denied', 'Access Denied'), ('export_denied', 'Export Denied'), ('feature_denied', 'Feature Denied'), ('limit_reached', 'Limit Reached'), ('plan_changed', 'Plan Changed'), ('upgraded', 'Upgraded'), ('downgraded', 'Downgraded')], db_index=True, max_length=32)),
                ('feature_key', models.CharField(blank=True, default='', max_length=64)),
                ('report_key', models.CharField(blank=True, default='', max_length=64)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_events', to='businesses.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlement_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'event_type', 'created_at'], name='reports_ent_busines_003f17_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_key', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('export', 'Exported'), ('schedule', 'Scheduled'), ('denied', 'Access Denied')], db_index=True, max_length=16)),
                ('format', models.CharField(blank=True, default='', max_length=8)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_usage', to='businesses.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'report_key', 'action'], name='reports_rep_busines_143aec_idx'), models.Index(fields=['business', 'action', 'created_at'], name='reports_rep_busines_a02386_idx')],
            },
        ),
    ]
