# Generated by Django 5.1.15 on 2026-09-29 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
