# Generated by Django 5.1.15 on 2026-09-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='report_scope',
            field=models.CharField(choices=[('OWN', 'Own records only'), ('TEAM', 'Team'), ('BRANCH', 'Assigned branches'), ('ALL_BUSINESS', 'Whole business')], default='ALL_BUSINESS', max_length=16),
        ),
    ]
