# Generated by Django 5.1.15 on 2026-09-29 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('low_stock', 'Low Stock'), ('sale_completed', 'Sale Completed'), ('payment_received', 'Payment Received'), ('invoice_overdue', 'Invoice Overdue'), ('staff_invitation', 'Staff Invitation'), ('security', 'Security Event'), ('subscription', 'Subscription Event'), ('system', 'System Announcement')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at', 'created_at'], name='notificatio_user_id_478247_idx'), models.Index(fields=['business', 'type', 'created_at'], name='notificatio_busines_c3f355_idx')],
            },
        ),
    ]
